# Generated by Django 4.2.11 on 2026-04-13 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_product_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('units_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('orders_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_performances', to='stores.shopifystore')),
            ],
            options={
                'ordering': ['-revenue'],
                'unique_together': {('store', 'shopify_product_id', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='DailyRevenueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('orders_count', models.IntegerField(default=0)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('aov', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_snapshots', to='stores.shopifystore')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['store', 'date'], name='analytics_d_store_i_04298b_idx')],
                'unique_together': {('store', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_customer_id', models.BigIntegerField()),
                ('segment', models.CharField(choices=[('new', 'New'), ('returning', 'Returning'), ('at_risk', 'At Risk'), ('lost', 'Lost')], max_length=20)),
                ('ltv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('orders_count', models.IntegerField(default=0)),
                ('last_order_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_segments', to='stores.shopifystore')),
            ],
            options={
                'ordering': ['-ltv'],
                'unique_together': {('store', 'shopify_customer_id')},
            },
        ),
    ]
