# Generated by Django 4.2.11 on 2026-04-13 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('orders', 'Orders'), ('products', 'Products'), ('customers', 'Customers')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('cursor', models.TextField(blank=True)),
                ('records_synced', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='stores.shopifystore')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('product_type', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='active', max_length=50)),
                ('variants', models.JSONField(default=list)),
                ('shopify_created_at', models.DateTimeField()),
                ('shopify_updated_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.shopifystore')),
            ],
            options={
                'ordering': ['-shopify_created_at'],
                'unique_together': {('store', 'shopify_id')},
            },
        ),
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.BigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('financial_status', models.CharField(blank=True, max_length=50)),
                ('fulfillment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('line_items', models.JSONField(default=list)),
                ('shopify_created_at', models.DateTimeField()),
                ('shopify_updated_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.shopifystore')),
            ],
            options={
                'ordering': ['-shopify_created_at'],
                'indexes': [models.Index(fields=['store', 'shopify_created_at'], name='ingestion_s_store_i_cc5c34_idx'), models.Index(fields=['store', 'customer_id'], name='ingestion_s_store_i_d016ea_idx')],
                'unique_together': {('store', 'shopify_id')},
            },
        ),
        migrations.CreateModel(
            name='ShopifyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.BigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('orders_count', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('shopify_created_at', models.DateTimeField()),
                ('shopify_updated_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='stores.shopifystore')),
            ],
            options={
                'ordering': ['-shopify_created_at'],
                'indexes': [models.Index(fields=['store', 'shopify_created_at'], name='ingestion_s_store_i_b77072_idx')],
                'unique_together': {('store', 'shopify_id')},
            },
        ),
    ]
